/**
 * Copyright (c) 2017 Enzien Audio, Ltd.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 * 
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER
 */

#ifndef _HEAVY_CONTEXT_WAKEFIELD_HPP_
#define _HEAVY_CONTEXT_WAKEFIELD_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlPrint.h"
#include "HvControlRandom.h"
#include "HvControlBinop.h"
#include "HvControlVar.h"
#include "HvControlSystem.h"
#include "HvControlSlice.h"
#include "HvSignalVar.h"
#include "HvSignalPhasor.h"
#include "HvControlDelay.h"
#include "HvControlIf.h"
#include "HvSignalCPole.h"
#include "HvMath.h"
#include "HvControlUnop.h"
#include "HvControlCast.h"
#include "HvSignalDel1.h"

class Heavy_wakefield : public HeavyContext {

 public:
  Heavy_wakefield(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_wakefield();

  const char *getName() override { return "wakefield"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;

  

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cBinop_Jx8go_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_jQbN1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jFCri_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bDXt8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jAwDB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ru44g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_rVue6_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cReceive_7fwhc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qDJ1R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tjekt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_GtmPO_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_Xm7hh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_v9LPI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DGga0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9mOAM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3eB0Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_iLlWn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jjrL7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_QaH8D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_MTiga_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_r4qFT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_1XLMu_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_YyI1K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_F1Tsl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_yaZAQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_g64OC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZYXCF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_r4Xwx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_V22xB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zN3WQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QTkvD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_s4FAs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_h9gH8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_l6Egw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_miGc8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3Dwvz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gb6N4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_UVB5b_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dIMzi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Tg3Wo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8upYz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gbuOZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ApMXf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_U4PCC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xUaCr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_qcVoz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_e1UAE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JHTjn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4ORgO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_J2l9N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_KDS6G_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_ulHK1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KpXew_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hzElN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Fv99o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FLw84_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_hyqmS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6BQWG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Iq1OV_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_GuIOd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_VDDNt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_42Ur4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_95gSC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VLniO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_ZCpew_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_TkWyc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_QQL0C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nzjwg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_fMGs3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2vwsb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_KTmkg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_af0UZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aWxDT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_XDroK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FdhnF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_OCDwj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NkRfS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TfO4v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_TpPC0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GXByt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_8hfse_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_L7pKC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gUACK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bQaB1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_yjUQ5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_dpVd9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cUnop_LX4MD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iFU2M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_c2LW3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ia2fS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OTS1e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PPQ7W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_fjSKr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_uYDDG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_rKpfR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rCKO3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UXVsd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_o6aA7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_wwXxh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HfBrz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NaIZJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qxE0Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_FHmvm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_WCWtm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_uBKsQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cVar_ixRcl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_thCjP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_13dmV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4vxgS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_X6o8R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_0tU7l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LOK00_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gLxfZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bbCeU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_OJixv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5Umnj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jNK8r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nEChs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3cqs0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SsIaY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SMgVh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_C4oew_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XYNcv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CX02Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_i04ZR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_agNLd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_iT45G_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_TgTJ7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pH4IV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aMq9n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lknzB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_oXmGd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_neXjW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_kOBEl_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSwitchcase_3428y_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_GiIIl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nStw1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZklLd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_VG6Y3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6tQe3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ZkaDU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Rt1ao_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qQrbf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_F1zLf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qVJJu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vtgX1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_U4lyL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_NL2Nz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aPrIA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_80zbo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_delQk_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_mw2OH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DTHD5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_0LC8p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ym0Cu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gyUAk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SjS4i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OLu2p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_dRaLr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Xk7KW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ikwSg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_knjMw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GDBNO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VH6Tt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_NWfpL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fLkVl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MCfhk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_L7qOO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hFPvL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1jhLc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7vKYJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9vAoI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_fayGi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EXzlM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_e21bA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_CWND7_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_Gpdln_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FEeT4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_x09SE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_OELfl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qLHf0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_iSIwd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_Hn6n4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_x0BVI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_5uch5_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_qxuUl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0K9OV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7jf1q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1Wboi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aU7hK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_aoTtz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kDQXP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KdGat_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_X0N2U_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_7CA8z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_UGNhS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Uf4Iy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5uL7V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sWHSx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_FNegX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_WWYZZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kNM4y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_njZhi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_HPuAs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_wNZEY_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_tEimb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WPRA0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_I0MHz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mvNa5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CLSYW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KGIor_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yKB7Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AoTmb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KlWQr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_GaUBM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_NLr5R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zkku7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oNv7Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6MZ2u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_W2m9m_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_LdkJd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7YUEq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4KWfC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RHhfs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XWGta_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pQO1V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mPVum_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KQu4v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_juki4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_puRxt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7Q3Cy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ju6BO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OYZgz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_TVD1y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IPgMS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sq7eL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XXCeY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_IrrSp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_TtrHx_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_8iuwe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3lpdS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QT8yo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_vGyhC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_a3PqO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_aK6V4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_WIpkU_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_CDay3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lMb8E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hT4T6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8CljT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_VuCZX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_nrnUw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_e7OUm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rN078_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_jegWw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5wRHY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_SajfP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1ESR8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_5i9xa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_mq08e_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_WfdM5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_avKzd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_krnJY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gfE1F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yPvyC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_OFY8N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_LGXPE_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_sHAIt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xRscD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_p0QsU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2Vbhw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_MEAao_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DJOgy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pf9QI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Mg080_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_jEv4L_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mvarx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2CnAA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fXeXM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9kCmS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_xK8BK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gLt5c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_QTWh0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_QTnLw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_t088E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cjXQF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_C9dSO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DNDOu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BNUwC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_cDZrC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_zWmgn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Xy5yV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qmO42_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vgOrM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pkkp6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JtJdV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IwoCC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ouv02_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_362FU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1oLAk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZIjvw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_5AQFQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_BHkoM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jrtEP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Oz3bH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_roMR0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lGndJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rVljY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HSJS1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_84WzQ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_WDeiq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_o65Q5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uWcOw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_x7ejE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_RzLfp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9RUci_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_Je6Du_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9XQpg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_4EjU0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iQUOC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ahJJG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LRtwt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_txT7B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_4Qe04_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_XlNTg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_kr4Uw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_T8hmv_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_LEebJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_jD6fJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_etnw2_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalPhasor sPhasor_hZJCY;
  SignalPhasor sPhasor_Asdn2;
  SignalPhasor sPhasor_GAkSZ;
  SignalPhasor sPhasor_YJh8Y;
  SignalPhasor sPhasor_Bfyxp;
  SignalCPole sCPole_NBm2a;
  ControlVar cVar_jQbN1;
  SignalVarf sVarf_DS5JW;
  ControlDelay cDelay_v9LPI;
  ControlBinop cBinop_DGga0;
  ControlBinop cBinop_3eB0Q;
  ControlVar cVar_iLlWn;
  ControlVar cVar_QaH8D;
  ControlVar cVar_MTiga;
  ControlBinop cBinop_r4qFT;
  ControlSlice cSlice_YyI1K;
  ControlSlice cSlice_F1Tsl;
  ControlBinop cBinop_g64OC;
  ControlVar cVar_ZYXCF;
  ControlBinop cBinop_r4Xwx;
  ControlBinop cBinop_V22xB;
  ControlBinop cBinop_zN3WQ;
  ControlBinop cBinop_QTkvD;
  ControlVar cVar_UVB5b;
  ControlBinop cBinop_Tg3Wo;
  ControlBinop cBinop_8upYz;
  ControlBinop cBinop_gbuOZ;
  ControlVar cVar_ApMXf;
  ControlBinop cBinop_xUaCr;
  ControlBinop cBinop_4ORgO;
  ControlVar cVar_FLw84;
  ControlSlice cSlice_VDDNt;
  ControlSlice cSlice_42Ur4;
  ControlVar cVar_95gSC;
  ControlBinop cBinop_VLniO;
  ControlBinop cBinop_TkWyc;
  ControlBinop cBinop_nzjwg;
  ControlDelay cDelay_fMGs3;
  ControlBinop cBinop_FdhnF;
  ControlRandom cRandom_OCDwj;
  ControlDelay cDelay_TpPC0;
  ControlBinop cBinop_L7pKC;
  ControlDelay cDelay_yjUQ5;
  ControlBinop cBinop_iFU2M;
  ControlRandom cRandom_c2LW3;
  ControlBinop cBinop_PPQ7W;
  ControlVar cVar_rKpfR;
  ControlBinop cBinop_UXVsd;
  ControlBinop cBinop_o6aA7;
  ControlVar cVar_wwXxh;
  ControlSlice cSlice_FHmvm;
  ControlSlice cSlice_WCWtm;
  ControlVar cVar_ixRcl;
  ControlBinop cBinop_thCjP;
  ControlSlice cSlice_X6o8R;
  ControlSlice cSlice_0tU7l;
  ControlBinop cBinop_LOK00;
  ControlVar cVar_OJixv;
  ControlBinop cBinop_jNK8r;
  ControlBinop cBinop_SMgVh;
  ControlBinop cBinop_C4oew;
  ControlBinop cBinop_CX02Q;
  ControlVar cVar_pH4IV;
  ControlBinop cBinop_lknzB;
  ControlVar cVar_oXmGd;
  ControlBinop cBinop_nStw1;
  ControlBinop cBinop_ZklLd;
  ControlDelay cDelay_VG6Y3;
  ControlBinop cBinop_qQrbf;
  ControlVar cVar_F1zLf;
  ControlBinop cBinop_qVJJu;
  ControlBinop cBinop_vtgX1;
  SignalVarf sVarf_TmfbZ;
  ControlDelay cDelay_mw2OH;
  ControlVar cVar_0LC8p;
  ControlVar cVar_ym0Cu;
  SignalVarf sVarf_R03Cn;
  ControlBinop cBinop_ikwSg;
  SignalVarf sVarf_n4Fvw;
  ControlIf cIf_knjMw;
  ControlBinop cBinop_GDBNO;
  ControlBinop cBinop_VH6Tt;
  ControlVar cVar_NWfpL;
  ControlBinop cBinop_MCfhk;
  ControlBinop cBinop_L7qOO;
  SignalVarf sVarf_saPtp;
  ControlBinop cBinop_1jhLc;
  SignalVarf sVarf_rTenm;
  ControlBinop cBinop_7vKYJ;
  ControlBinop cBinop_Gpdln;
  ControlBinop cBinop_FEeT4;
  ControlVar cVar_x09SE;
  ControlDelay cDelay_OELfl;
  SignalVarf sVarf_ZoifP;
  ControlVar cVar_iSIwd;
  ControlDelay cDelay_x0BVI;
  ControlVar cVar_UGNhS;
  ControlBinop cBinop_5uL7V;
  ControlSlice cSlice_FNegX;
  ControlSlice cSlice_WWYZZ;
  ControlBinop cBinop_kNM4y;
  ControlDelay cDelay_njZhi;
  ControlVar cVar_HPuAs;
  ControlBinop cBinop_CLSYW;
  ControlBinop cBinop_KGIor;
  ControlVar cVar_NLr5R;
  ControlBinop cBinop_LdkJd;
  ControlVar cVar_7YUEq;
  ControlBinop cBinop_4KWfC;
  ControlBinop cBinop_RHhfs;
  ControlBinop cBinop_XWGta;
  ControlVar cVar_pQO1V;
  ControlBinop cBinop_mPVum;
  ControlBinop cBinop_KQu4v;
  ControlBinop cBinop_juki4;
  ControlVar cVar_7Q3Cy;
  ControlBinop cBinop_XXCeY;
  ControlSlice cSlice_IrrSp;
  ControlSlice cSlice_8iuwe;
  ControlBinop cBinop_3lpdS;
  ControlBinop cBinop_QT8yo;
  ControlVar cVar_vGyhC;
  ControlDelay cDelay_CDay3;
  ControlRandom cRandom_VuCZX;
  ControlBinop cBinop_e7OUm;
  SignalVarf sVarf_sWuUR;
  ControlBinop cBinop_rN078;
  ControlVar cVar_jegWw;
  ControlBinop cBinop_5wRHY;
  ControlRandom cRandom_SajfP;
  ControlBinop cBinop_1ESR8;
  ControlDelay cDelay_krnJY;
  ControlBinop cBinop_gfE1F;
  ControlDelay cDelay_OFY8N;
  ControlBinop cBinop_2Vbhw;
  ControlBinop cBinop_Mg080;
  ControlVar cVar_jEv4L;
  ControlBinop cBinop_fXeXM;
  ControlVar cVar_9kCmS;
  ControlBinop cBinop_gLt5c;
  ControlVar cVar_QTnLw;
  ControlBinop cBinop_t088E;
  ControlBinop cBinop_cjXQF;
  ControlBinop cBinop_DNDOu;
  ControlBinop cBinop_BNUwC;
  ControlSlice cSlice_cDZrC;
  ControlSlice cSlice_zWmgn;
  ControlBinop cBinop_qmO42;
  ControlBinop cBinop_JtJdV;
  ControlVar cVar_362FU;
  ControlBinop cBinop_HSJS1;
  ControlBinop cBinop_o65Q5;
  ControlBinop cBinop_uWcOw;
  ControlDelay cDelay_Je6Du;
  ControlVar cVar_9XQpg;
  ControlVar cVar_4EjU0;
  ControlBinop cBinop_iQUOC;
  ControlVar cVar_ahJJG;
  ControlBinop cBinop_LRtwt;
  ControlSlice cSlice_XlNTg;
  ControlSlice cSlice_kr4Uw;
  SignalVarf sVarf_tTMzR;
  ControlVar cVar_jD6fJ;
  ControlBinop cBinop_etnw2;
};

#endif // _HEAVY_CONTEXT_WAKEFIELD_HPP_
