/**
 * Copyright (c) 2017 Enzien Audio, Ltd.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 * 
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER
 */

#ifndef _HEAVY_CONTEXT_WAKEFIELD_HPP_
#define _HEAVY_CONTEXT_WAKEFIELD_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlRandom.h"
#include "HvControlBinop.h"
#include "HvControlVar.h"
#include "HvControlSystem.h"
#include "HvControlSlice.h"
#include "HvSignalVar.h"
#include "HvSignalPhasor.h"
#include "HvControlDelay.h"
#include "HvControlIf.h"
#include "HvSignalCPole.h"
#include "HvMath.h"
#include "HvControlUnop.h"
#include "HvControlCast.h"
#include "HvSignalDel1.h"

class Heavy_wakefield : public HeavyContext {

 public:
  Heavy_wakefield(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_wakefield();

  const char *getName() override { return "wakefield"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;

  

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cVar_FQ0fc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_5CqqX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_803a1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wQ4Su_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_xqeAn_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_ZleGm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eC6MF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Cblx0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_L9FmR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_pk2YN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_5VPka_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AdgI3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UdLmg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_yqrnD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_oiXMf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Sm7iO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_GjNtD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_VKgFa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yvTdX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Co3Xx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Qw0EI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_uei9c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sHegG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_KHk21_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Ekwk9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_8ifZD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Xc8ne_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UAMN7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ezzso_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_sIYGu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FlYOr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_1rhmu_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_EafXp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_uKzLw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_njtzp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GeXf3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_R6alg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Jp3ps_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AYuVQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HsGUF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BDpRM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_4H1Ca_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KJzHX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_p9bvN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSystem_ffGQg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DnW96_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_6cuFK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ok2x4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ykJms_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ariWu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_noECo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5x797_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W0Zw0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_PszzM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pk63J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_c4Xgy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_AVTBo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jyJSC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_j1aVN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5dnHB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LB1pW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_uvsUX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vvgGs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CDJY8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lkf3x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_z3VcB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4U574_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_MxZAH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_DRWVZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Rl8Ln_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oKiF6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_es5os_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_NHifJ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_Y6XQ6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_tP4LJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_oeoEr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_f08iC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_K3dgo_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cVar_amRDD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_Z312h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mEwli_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RPmKt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6cO5X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_acgcO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_eCQ10_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Y4SHA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7Dnb5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3v0YC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EGCWF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FVre6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lSlxc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_R3mz3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yzS0h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ba8e0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AytYM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_HVs9K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_6VlNq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_770on_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mMjso_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4iC6S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_LPBfj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vH3hF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_6It7r_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JKYdA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZTS2L_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mLNoD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CDwXm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_TwGmR_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_g4yLe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_A98jH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_q0zlZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_DRcZO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_w28jL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_voB3v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FU8k6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LHXhq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_X6lUA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_h3nYr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_vFJg8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rTCcM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yMmmK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Xx1jF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tacmX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_k18M1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hF84I_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_kWxat_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LFRlu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_qsZJR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fgCS9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uClm7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_65TjJ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cVar_onxLx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_k7fqY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_kbEEk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_HMnZk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_PQSkd_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_RjCdW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WREyK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_e9gWP_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_lDrJd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_GFfKi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7gx0c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_e8Mld_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZUdXn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GIFo1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_zLGs5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_vhwTC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5gqMQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_jCgHO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_MrqMM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_wV3ap_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9XrAY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rf6Ta_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_AF3A7_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_Hb29x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5sYis_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vOoZA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3Q7KD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_vzjTw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_IrQNI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hLsVw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XsNYN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_wHw8U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_FQs7V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qplx5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GgmOQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_k76tD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Lo5W5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iHbXH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LCuNU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3sgQp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_pmBUO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_rXmsW_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_h15hQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_HXU26_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dzudZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_hy0la_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_LdUpL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_yXFGM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pmV1D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_LFA0Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_TNaqv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ABXxf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_qgQI9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0DMOr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_agxl3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_CD5iP_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_LopJy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IHVdZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mD61D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uuO79_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_dWjcn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PB6zy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fWyM5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ybuYN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WGgwD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MeYeQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8bj2E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qqCA1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_oie8N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_1lemr_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_iXewc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_35VIn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_A58DI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9FyxJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CzTbB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MnlLO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_GRt2V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Pt1qb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_qN7Xf_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_jJJX1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Xqeov_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7KwZt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PdWMV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_FgV5Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TsxbX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TmKNz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_44YAN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_byzq9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Z0hzp_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cVar_HHqDI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gohHs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_avrwU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nm19K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8uNOu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OrFBV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CNzJm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fxA02_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_7mMO5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_e5d2D_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rCChL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Uuh5y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Vu8FI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ETfMt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_fA6mn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_K3AZq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_rvY7N_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_mCC3W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pWUI2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_XUL8o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aFqoR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_gAqMN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_e4CWo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lh4it_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_ikWJZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XZYgp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_zpe8E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mjOBz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1ziMk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_xvJXb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_N3ilr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RFAxd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_lubKV_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_lyP5K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_vvWlW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_woNax_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CD9jW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_hmeAQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_EzBUp_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_SxiiV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nLQqT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_N3n9E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_deatz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_vnUT7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tdYxW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_8NBWk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_30tyo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_KHwPZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KtpV7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_5nVJA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_PETJs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_FQfEY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_pq7j9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_aoST8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_YdkMW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_SYnR3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LJxxJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lS1jG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nZa0h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_p6nlH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kO3fi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6a3qv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_txZAV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_H8AIB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bFC0w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_F6U3X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0TVSM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GVCLx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_jFrtB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_BUtG2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tL7BH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oXUl9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lFIc3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_s9jSC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_i9MY7_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_8cvGR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VDx3q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IdRcN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_TQH1H_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_lp8ED_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_2fSK1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Aat7f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EDi7Y_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_gNXqo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_k2pHu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nQRfc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3s7w3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pTuc0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_43xC9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WASwT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tXFLZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_6zM26_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ksn5B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nOKwK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ntlfx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_HA4FC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mBJlg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ckd7z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_mSpPd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_9xFF3_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSystem_pgCpI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_w58iy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_L6lfd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_D1exW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZbAaP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_9Vdyx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CzfRr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_fgwcu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_BvpO4_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);

  // objects
  SignalPhasor sPhasor_ftsRB;
  SignalPhasor sPhasor_Q8cNj;
  SignalPhasor sPhasor_xdUes;
  SignalPhasor sPhasor_HIn0f;
  SignalPhasor sPhasor_hOSTE;
  SignalCPole sCPole_B0Kyn;
  ControlVar cVar_FQ0fc;
  ControlDelay cDelay_ZleGm;
  ControlBinop cBinop_AdgI3;
  ControlBinop cBinop_UdLmg;
  ControlSlice cSlice_GjNtD;
  ControlSlice cSlice_VKgFa;
  ControlBinop cBinop_yvTdX;
  ControlVar cVar_Co3Xx;
  ControlBinop cBinop_Qw0EI;
  ControlBinop cBinop_uei9c;
  ControlBinop cBinop_sHegG;
  ControlSlice cSlice_KHk21;
  ControlSlice cSlice_8ifZD;
  ControlBinop cBinop_UAMN7;
  ControlVar cVar_sIYGu;
  ControlVar cVar_uKzLw;
  ControlVar cVar_njtzp;
  ControlBinop cBinop_GeXf3;
  ControlVar cVar_Jp3ps;
  ControlVar cVar_AYuVQ;
  ControlBinop cBinop_BDpRM;
  ControlDelay cDelay_4H1Ca;
  ControlVar cVar_6cuFK;
  ControlBinop cBinop_ok2x4;
  ControlBinop cBinop_ykJms;
  ControlBinop cBinop_ariWu;
  ControlBinop cBinop_W0Zw0;
  ControlBinop cBinop_5dnHB;
  ControlBinop cBinop_lkf3x;
  SignalVarf sVarf_cZQaS;
  ControlVar cVar_z3VcB;
  ControlBinop cBinop_4U574;
  ControlRandom cRandom_DRWVZ;
  ControlDelay cDelay_es5os;
  ControlBinop cBinop_Y6XQ6;
  ControlVar cVar_amRDD;
  ControlDelay cDelay_Z312h;
  ControlBinop cBinop_mEwli;
  ControlBinop cBinop_RPmKt;
  ControlBinop cBinop_6cO5X;
  ControlVar cVar_7Dnb5;
  ControlBinop cBinop_EGCWF;
  SignalVarf sVarf_3eq55;
  ControlBinop cBinop_R3mz3;
  ControlBinop cBinop_yzS0h;
  SignalVarf sVarf_Ybc5G;
  SignalVarf sVarf_uBN1s;
  SignalVarf sVarf_F2I5S;
  ControlVar cVar_AytYM;
  ControlIf cIf_HVs9K;
  ControlBinop cBinop_6VlNq;
  ControlBinop cBinop_770on;
  ControlBinop cBinop_vH3hF;
  ControlVar cVar_6It7r;
  ControlBinop cBinop_JKYdA;
  ControlBinop cBinop_ZTS2L;
  ControlDelay cDelay_g4yLe;
  ControlRandom cRandom_q0zlZ;
  ControlBinop cBinop_w28jL;
  ControlVar cVar_FU8k6;
  ControlBinop cBinop_h3nYr;
  ControlVar cVar_vFJg8;
  ControlVar cVar_k18M1;
  ControlBinop cBinop_hF84I;
  ControlVar cVar_qsZJR;
  ControlVar cVar_onxLx;
  ControlSlice cSlice_kbEEk;
  ControlSlice cSlice_HMnZk;
  ControlBinop cBinop_RjCdW;
  ControlVar cVar_GFfKi;
  ControlBinop cBinop_7gx0c;
  ControlBinop cBinop_ZUdXn;
  ControlBinop cBinop_GIFo1;
  ControlVar cVar_zLGs5;
  ControlBinop cBinop_vhwTC;
  ControlBinop cBinop_5gqMQ;
  ControlDelay cDelay_wV3ap;
  ControlBinop cBinop_Hb29x;
  ControlBinop cBinop_5sYis;
  ControlSlice cSlice_vzjTw;
  ControlSlice cSlice_IrQNI;
  ControlBinop cBinop_XsNYN;
  ControlBinop cBinop_GgmOQ;
  ControlVar cVar_k76tD;
  ControlBinop cBinop_LCuNU;
  ControlBinop cBinop_3sgQp;
  ControlDelay cDelay_pmBUO;
  SignalVarf sVarf_JAzpx;
  ControlBinop cBinop_hy0la;
  ControlVar cVar_LdUpL;
  ControlVar cVar_pmV1D;
  ControlVar cVar_LFA0Q;
  ControlVar cVar_qgQI9;
  ControlBinop cBinop_LopJy;
  ControlBinop cBinop_fWyM5;
  ControlBinop cBinop_WGgwD;
  ControlBinop cBinop_qqCA1;
  ControlSlice cSlice_oie8N;
  ControlSlice cSlice_iXewc;
  ControlDelay cDelay_35VIn;
  ControlVar cVar_A58DI;
  ControlBinop cBinop_9FyxJ;
  ControlBinop cBinop_MnlLO;
  ControlBinop cBinop_Xqeov;
  ControlBinop cBinop_TsxbX;
  ControlBinop cBinop_TmKNz;
  ControlVar cVar_44YAN;
  ControlVar cVar_HHqDI;
  ControlBinop cBinop_avrwU;
  ControlBinop cBinop_8uNOu;
  ControlBinop cBinop_CNzJm;
  ControlSlice cSlice_7mMO5;
  ControlSlice cSlice_e5d2D;
  ControlBinop cBinop_rCChL;
  ControlBinop cBinop_Uuh5y;
  ControlDelay cDelay_fA6mn;
  SignalVarf sVarf_Xa5rC;
  ControlVar cVar_XUL8o;
  ControlDelay cDelay_e4CWo;
  ControlBinop cBinop_XZYgp;
  ControlRandom cRandom_zpe8E;
  ControlBinop cBinop_1ziMk;
  ControlBinop cBinop_N3ilr;
  ControlBinop cBinop_RFAxd;
  ControlDelay cDelay_vvWlW;
  SignalVarf sVarf_Pg8kc;
  ControlDelay cDelay_hmeAQ;
  ControlBinop cBinop_N3n9E;
  ControlRandom cRandom_vnUT7;
  ControlBinop cBinop_tdYxW;
  ControlVar cVar_KHwPZ;
  ControlBinop cBinop_KtpV7;
  ControlBinop cBinop_5nVJA;
  ControlSlice cSlice_PETJs;
  ControlSlice cSlice_FQfEY;
  ControlBinop cBinop_SYnR3;
  ControlBinop cBinop_LJxxJ;
  ControlBinop cBinop_lS1jG;
  ControlBinop cBinop_p6nlH;
  ControlVar cVar_txZAV;
  ControlBinop cBinop_H8AIB;
  ControlVar cVar_F6U3X;
  ControlBinop cBinop_0TVSM;
  ControlBinop cBinop_GVCLx;
  ControlSlice cSlice_jFrtB;
  ControlSlice cSlice_BUtG2;
  ControlVar cVar_2fSK1;
  ControlBinop cBinop_gNXqo;
  ControlVar cVar_pTuc0;
  ControlVar cVar_43xC9;
  ControlVar cVar_WASwT;
  ControlBinop cBinop_tXFLZ;
  ControlDelay cDelay_HA4FC;
  ControlBinop cBinop_mBJlg;
  ControlBinop cBinop_ckd7z;
  ControlVar cVar_mSpPd;
  ControlBinop cBinop_D1exW;
};

#endif // _HEAVY_CONTEXT_WAKEFIELD_HPP_
