/**
 * Copyright (c) 2017 Enzien Audio, Ltd.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 * 
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER
 */

#ifndef _HEAVY_CONTEXT_WAKEFIELD_HPP_
#define _HEAVY_CONTEXT_WAKEFIELD_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlRandom.h"
#include "HvControlBinop.h"
#include "HvControlDelay.h"
#include "HvControlSystem.h"
#include "HvControlSlice.h"
#include "HvSignalVar.h"
#include "HvSignalPhasor.h"
#include "HvControlVar.h"
#include "HvControlIf.h"
#include "HvSignalCPole.h"
#include "HvMath.h"
#include "HvControlUnop.h"
#include "HvControlCast.h"
#include "HvSignalDel1.h"

class Heavy_wakefield : public HeavyContext {

 public:
  Heavy_wakefield(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_wakefield();

  const char *getName() override { return "wakefield"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;

  

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cVar_zBK0C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_R4iik_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_kcC6M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_ZGaxK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_A6c8w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NsieA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nW93z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_W3Hx5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_JIIDg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_XtwxH_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cReceive_uh1tz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7x2xi_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_WlKQp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_L5qlf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_3Gyyb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Hihv0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rXwy9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_sAIql_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Bsnqf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BVFAC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zK4gJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_VbgGw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kLHt8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XRlGo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bChbl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_7JVSB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_HKAHd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ylu4t_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rmFnu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_X6suP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_MVUOI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Eoqjn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zPeLH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_R6H8T_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bpbX5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_9UcpM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tGnyr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tPg4N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_jCZU9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tubrP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_BhCmf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_vkDEK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_GhS9t_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_ttSqd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_YCM2N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VdVQS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_oOIxF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_6EvqE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4Udpn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_wZEg9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_b8oh7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PuPTF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_mhcmP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_hNATR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4aoNT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_zA4F2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bl4b4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_D00Ye_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_8cl4A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tDzHk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_KsTNI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EmE14_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_ZeI1T_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_kOSFx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5ecej_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6aYoE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_a9YT3_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_Irurq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_IiTyS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NbA8a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Wh4Y6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SdPBQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7G8JG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_K3KPw_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_ysq9K_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_LVnPT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_yqjbJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_bwFoI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DMxjb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_a2u1u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Mykg8_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cRandom_SvyhU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TA5g6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_VSzGF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_3QVSU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_EPGLU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_50wkU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_czN1q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_kpgL5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_eXTrH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FPfO1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_mmir6_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_Ayv2z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_s1QG2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_bXrcf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KHXtC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_NzclX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_gj8rW_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_ts0cK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WcMS2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_w7kkI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kXEy9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_BnNJO_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_XvBL5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xIRaK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tjiYt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_6WTgM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VI9yJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ybjbn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ADDIM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_y4fEc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nwG2M_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_6XvgS_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_42QRe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_MSoVQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_BQ2m2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VOJqT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_H2sYI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_61Si7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_TyYI9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DFJvZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rE1eD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_4Wg4Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_T3B23_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CduV2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cC9v0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_m4O86_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kZS4C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nreyz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_D2VOB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_v5m3C_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2lByX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_iT95N_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Pzd8i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_4TIzN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_sVisa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_NxdJl_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSystem_Nw1t6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ekCJn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MpTgp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_pL9zd_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_vx6Rm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oKCyb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_j0CAL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_MYGUE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tFHe1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PWOKb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_XZm3l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DwW0q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_fai4H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_sg4gK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oVj2i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_t2yG8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1Bzrq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_6lgaE_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_YUSvi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_05DMw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_j8ss1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2fjof_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_Ixl9n_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1LuGZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_cSaym_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Ryfrz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_RT3Ch_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_njUCP_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_HtUnI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_W0JTy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_0ICae_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_CmD2J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Ele0d_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_G7Z8e_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_LPH05_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_okwor_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_IZCUn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_XnUkR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jkcg6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_qK6KQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_pze9F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0EBQ6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_WXyBp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_FehQd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_CVRsN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_opQcJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_xYcWL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_E83By_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nFpFV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_W60pM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NZ8W6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_9bkIH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_89H8e_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_cEreX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_D4jLi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NaG9f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_rDDt3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_3Spj7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_Lt71x_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NlSzA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_cYL1p_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_KxkUe_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mpZor_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_UJFtt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_f0Pks_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GAXHy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rLKie_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KvLz1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7rIaR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_j9gmk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_1aLPc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_H01Uf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_eIP2f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_stCbS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_CfPwW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_KPv2h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_sgkx1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_5AJYN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_KPeAz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7lchN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fYuea_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_D3vtt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yeQkv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_U3nhW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_3VegM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_pwv2m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VDaCy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_a7cgX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_E3vuk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_ILYxk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_Wbuel_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8s88m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_y6imH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ez1hh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_iIqsH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_D7YgK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_YIhH3_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_5hZwI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tptmQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OD1Pa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7X4ku_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_A5SMf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_7KgAW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_3gdId_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_mSJeg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_uL6pD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_j9ATE_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_ZYcbU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3iVnT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_n96Mv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_WvKHm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_rXhJY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7gAUS_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cVar_VlTJq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SIYL6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1MVQc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2d8kY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_EMTwz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_M9dwY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FJLEK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ZWjYZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_7VTTN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_87rGm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3xj3A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7JGxQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_SrG4p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qBrvs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_rNYNo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_H1wPx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_lHHV3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_sVLmy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_feL8j_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ehk1J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_iBm7R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_cmkWQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_CXcfR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_byNRW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SgiuY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8UPwr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_SGUKN_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_bJpS5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_rjyTy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_2e0q9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_Ux2VG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_VmGgg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_gcHBP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_OyogB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_kLqaS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NemP4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dK59m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_l1Byy_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_DuPh9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_wtH6F_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_otdNI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7g8Y4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZWxm6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zkqgW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_C3XzC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_bTbnT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_9SshR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_aqs7U_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_yCnjb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_ZeMfa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YdSRB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_lxc8c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_JEsrZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gUD2J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_SNZ05_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FUAew_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_434hu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_EtTaV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_3ZRvH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rUCDi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zd81i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_OLwWU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_LNsr3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_freWP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_IgSko_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EdB4a_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_bYuha_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_e6YyH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_OLrKi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_UzJ2a_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_BCTyA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_cj6bc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_L0tZf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_aG4s0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_J5CZX_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_QdeRD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_KIy0R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_K8KD6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_TlVsM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_VtrS4_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_0SGgL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_jX0Wf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_v7dOR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RmCWR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FLxyL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_lOueF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_oJOzq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_h9rdr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Xwe2X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WdVel_sendMessage(HeavyContextInterface *, int, const HvMessage *);

  // objects
  SignalPhasor sPhasor_glGom;
  SignalPhasor sPhasor_HQdaM;
  SignalPhasor sPhasor_I1U7T;
  SignalPhasor sPhasor_wILZr;
  SignalPhasor sPhasor_gqPkj;
  SignalPhasor sPhasor_5rxoq;
  SignalCPole sCPole_Z5bbj;
  ControlVar cVar_zBK0C;
  ControlVar cVar_R4iik;
  ControlVar cVar_kcC6M;
  ControlDelay cDelay_3Gyyb;
  ControlBinop cBinop_rXwy9;
  ControlBinop cBinop_BVFAC;
  SignalVarf sVarf_RGOBs;
  ControlBinop cBinop_zK4gJ;
  ControlSlice cSlice_7JVSB;
  ControlSlice cSlice_HKAHd;
  ControlBinop cBinop_Ylu4t;
  ControlBinop cBinop_rmFnu;
  ControlVar cVar_X6suP;
  ControlBinop cBinop_Eoqjn;
  ControlBinop cBinop_9UcpM;
  ControlBinop cBinop_tPg4N;
  ControlBinop cBinop_tubrP;
  ControlSlice cSlice_BhCmf;
  ControlSlice cSlice_vkDEK;
  ControlVar cVar_oOIxF;
  ControlVar cVar_6EvqE;
  ControlBinop cBinop_4Udpn;
  ControlVar cVar_wZEg9;
  ControlBinop cBinop_mhcmP;
  ControlVar cVar_hNATR;
  ControlBinop cBinop_4aoNT;
  ControlDelay cDelay_zA4F2;
  ControlBinop cBinop_tDzHk;
  ControlVar cVar_KsTNI;
  ControlBinop cBinop_kOSFx;
  ControlBinop cBinop_NbA8a;
  ControlVar cVar_SdPBQ;
  ControlBinop cBinop_ysq9K;
  ControlVar cVar_yqjbJ;
  ControlDelay cDelay_bwFoI;
  ControlRandom cRandom_SvyhU;
  ControlBinop cBinop_TA5g6;
  ControlVar cVar_3QVSU;
  ControlVar cVar_50wkU;
  ControlSlice cSlice_kpgL5;
  ControlSlice cSlice_eXTrH;
  ControlDelay cDelay_ts0cK;
  ControlBinop cBinop_WcMS2;
  ControlBinop cBinop_w7kkI;
  ControlVar cVar_BnNJO;
  ControlBinop cBinop_XvBL5;
  ControlBinop cBinop_xIRaK;
  ControlBinop cBinop_tjiYt;
  ControlBinop cBinop_ybjbn;
  ControlVar cVar_MSoVQ;
  ControlBinop cBinop_BQ2m2;
  ControlVar cVar_TyYI9;
  ControlBinop cBinop_DFJvZ;
  ControlVar cVar_4Wg4Q;
  ControlBinop cBinop_m4O86;
  ControlBinop cBinop_kZS4C;
  ControlBinop cBinop_nreyz;
  ControlBinop cBinop_v5m3C;
  ControlVar cVar_iT95N;
  ControlBinop cBinop_Pzd8i;
  ControlSlice cSlice_4TIzN;
  ControlSlice cSlice_sVisa;
  ControlBinop cBinop_MpTgp;
  SignalVarf sVarf_BUAZD;
  ControlDelay cDelay_j0CAL;
  ControlBinop cBinop_MYGUE;
  ControlBinop cBinop_tFHe1;
  ControlRandom cRandom_sg4gK;
  ControlBinop cBinop_oVj2i;
  ControlDelay cDelay_YUSvi;
  ControlVar cVar_05DMw;
  ControlVar cVar_j8ss1;
  ControlBinop cBinop_2fjof;
  ControlDelay cDelay_Ixl9n;
  ControlBinop cBinop_1LuGZ;
  ControlVar cVar_cSaym;
  ControlBinop cBinop_HtUnI;
  ControlVar cVar_CmD2J;
  ControlVar cVar_Ele0d;
  SignalVarf sVarf_jbMVY;
  ControlVar cVar_G7Z8e;
  ControlVar cVar_XnUkR;
  SignalVarf sVarf_Jzfbm;
  ControlBinop cBinop_0EBQ6;
  ControlIf cIf_WXyBp;
  ControlBinop cBinop_FehQd;
  SignalVarf sVarf_yUml6;
  ControlBinop cBinop_CVRsN;
  SignalVarf sVarf_UC8By;
  ControlBinop cBinop_xYcWL;
  SignalVarf sVarf_G5TJv;
  ControlBinop cBinop_W60pM;
  ControlBinop cBinop_NZ8W6;
  ControlDelay cDelay_9bkIH;
  ControlBinop cBinop_NaG9f;
  ControlRandom cRandom_3Spj7;
  ControlDelay cDelay_Lt71x;
  ControlBinop cBinop_UJFtt;
  ControlBinop cBinop_KvLz1;
  ControlBinop cBinop_7rIaR;
  ControlVar cVar_j9gmk;
  ControlVar cVar_1aLPc;
  ControlVar cVar_H01Uf;
  ControlBinop cBinop_eIP2f;
  ControlDelay cDelay_sgkx1;
  ControlBinop cBinop_7lchN;
  ControlBinop cBinop_fYuea;
  ControlBinop cBinop_yeQkv;
  ControlVar cVar_pwv2m;
  ControlBinop cBinop_a7cgX;
  ControlVar cVar_8s88m;
  ControlBinop cBinop_5hZwI;
  ControlBinop cBinop_7X4ku;
  ControlBinop cBinop_A5SMf;
  ControlSlice cSlice_7KgAW;
  ControlSlice cSlice_3gdId;
  ControlBinop cBinop_3iVnT;
  ControlVar cVar_n96Mv;
  ControlSlice cSlice_WvKHm;
  ControlSlice cSlice_rXhJY;
  ControlVar cVar_VlTJq;
  ControlBinop cBinop_1MVQc;
  ControlBinop cBinop_2d8kY;
  ControlBinop cBinop_M9dwY;
  ControlVar cVar_FJLEK;
  SignalVarf sVarf_EFrNu;
  ControlBinop cBinop_87rGm;
  SignalVarf sVarf_mUiG1;
  ControlBinop cBinop_7JGxQ;
  ControlVar cVar_rNYNo;
  ControlBinop cBinop_lHHV3;
  ControlBinop cBinop_sVLmy;
  ControlBinop cBinop_iBm7R;
  ControlBinop cBinop_cmkWQ;
  ControlVar cVar_byNRW;
  ControlSlice cSlice_gcHBP;
  ControlSlice cSlice_OyogB;
  ControlBinop cBinop_kLqaS;
  ControlBinop cBinop_l1Byy;
  ControlBinop cBinop_DuPh9;
  ControlBinop cBinop_ZWxm6;
  ControlVar cVar_bTbnT;
  ControlDelay cDelay_9SshR;
  ControlBinop cBinop_aqs7U;
  ControlBinop cBinop_yCnjb;
  ControlBinop cBinop_ZeMfa;
  ControlVar cVar_YdSRB;
  ControlVar cVar_EtTaV;
  ControlVar cVar_3ZRvH;
  ControlBinop cBinop_zd81i;
  ControlVar cVar_LNsr3;
  ControlBinop cBinop_IgSko;
  ControlBinop cBinop_bYuha;
  ControlSlice cSlice_e6YyH;
  ControlSlice cSlice_OLrKi;
  ControlVar cVar_cj6bc;
  ControlBinop cBinop_L0tZf;
  ControlVar cVar_aG4s0;
  SignalVarf sVarf_gHznS;
  ControlDelay cDelay_KIy0R;
  ControlDelay cDelay_TlVsM;
  ControlBinop cBinop_RmCWR;
  ControlRandom cRandom_oJOzq;
  ControlBinop cBinop_h9rdr;
  ControlVar cVar_WdVel;
};

#endif // _HEAVY_CONTEXT_WAKEFIELD_HPP_
