/**
 * Copyright (c) 2017 Enzien Audio, Ltd.
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 * 
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE ENZIEN AUDIO HEAVY COMPILER
 */

#ifndef _HEAVY_CONTEXT_WAKEFIELD_HPP_
#define _HEAVY_CONTEXT_WAKEFIELD_HPP_

// object includes
#include "HeavyContext.hpp"
#include "HvControlRandom.h"
#include "HvControlBinop.h"
#include "HvControlVar.h"
#include "HvControlSystem.h"
#include "HvControlSlice.h"
#include "HvSignalVar.h"
#include "HvSignalPhasor.h"
#include "HvControlDelay.h"
#include "HvControlIf.h"
#include "HvSignalCPole.h"
#include "HvMath.h"
#include "HvControlUnop.h"
#include "HvControlCast.h"
#include "HvSignalDel1.h"

class Heavy_wakefield : public HeavyContext {

 public:
  Heavy_wakefield(double sampleRate, int poolKb=10, int inQueueKb=2, int outQueueKb=0);
  ~Heavy_wakefield();

  const char *getName() override { return "wakefield"; }
  int getNumInputChannels() override { return 0; }
  int getNumOutputChannels() override { return 2; }

  int process(float **inputBuffers, float **outputBuffer, int n) override;
  int processInline(float *inputBuffers, float *outputBuffer, int n) override;
  int processInlineInterleaved(float *inputBuffers, float *outputBuffer, int n) override;

  int getParameterInfo(int index, HvParameterInfo *info) override;

  

 private:
  HvTable *getTableForHash(hv_uint32_t tableHash) override;
  void scheduleMessageForReceiver(hv_uint32_t receiverHash, HvMessage *m) override;

  // static sendMessage functions
  static void cReceive_aOLLR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9NFjv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_vnFPf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_Z2yUY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_WVAce_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_duszf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_7dWL4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_yickW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5hbma_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_gn3LI_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_ZMxXM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0OQRE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_nQZFG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_3h0mR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_v8ZuM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_EF2Sc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fywD9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Wy7Ju_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YS56E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_sp8wQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_JyBRD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3VafA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_fos2S_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_5sIA3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rTnJV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ejRpv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_1rI9W_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XvJE2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xP21g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WHUIU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3xdpd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_0oX0u_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_L7LpR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_NzJcu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_EdHfp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BJLBt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7tiIj_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_tnmao_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PdC4B_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7Od2R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_Kv0OY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_TxbAK_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_QFGzm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_t4MMg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QKb85_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Mrmjk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_PEn4i_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_FQPu1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_DXKWd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_25bSX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_8VX1v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oW1Zx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_NQiBW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ZdABW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_kg4HZ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_xycem_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_lOsqV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_FWSDw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_n37uc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gfsoF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_MmdQ6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Lv4L4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_ZTFUx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_iP4L1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_GxKUP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QlpTT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_L5JO0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_s4Z1z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Pj6G7_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cVar_JOTXY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_c1fSq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Ard2p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_vb6sG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_3ooXL_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3RPP9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_hSBAr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_4dpmP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jsyUW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_NK4en_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_gPYKw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_q2SLd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7nrbA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_LirPc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_8H3aC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jGEuW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_v3xgY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_31qzD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_gdScj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_qHCbW_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_DBt9z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_LXXqh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2Toct_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Wh6OP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_DvzVb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1n63J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YFUfl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_muRgF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cIf_VMssB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_EWtkZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_gslwk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Dh5YM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jOmQS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_OSEed_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_b59SS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_nPYlv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Zexmn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_z9YIS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_AY8Uh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_HWvS4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_fIP0p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rL9I5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_SqakV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_JtjSa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Abyfp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_QSQ2k_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Rk3VK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_pQMK0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hz6ka_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_NOM4H_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cTMqr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_f97J6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_BGBvp_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cVar_eYgpj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_hNvuY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_zpqUW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_Xpo4m_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_2wyuM_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_VKlc6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_Eqsie_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_2sEDz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_10glQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_GW3Pi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_sEPUY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_fbTJf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_FL4ht_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_5KHRm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_di92Z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_KmGJr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_wpvkJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_0kY4R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_6pahf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_N8fN9_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_XMgpK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_3XxRX_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_jsBe3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pw47p_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_y4fyw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_gB4iq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_dC7h4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8SYZx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pTOIz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Eckjr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_KxOFP_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_9Fw1c_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_N3dVS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HJ6bk_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0Mz4O_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_nEmDI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_qkiWf_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_W9k71_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_WHrY2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_Qg8US_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_d6PPH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Yzewn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_7sp4G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_hUv6z_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0NnOY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_VfAcm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_iUizp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yyyVj_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_UfiIp_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_FE83A_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_je0M5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_2jGF4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_YNLN3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_NQ2cl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YYd6X_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_M1eXG_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_oPLhX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tTpWz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_P7BSw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_0d0l2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_KdFy6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_6G4Ne_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_FQ7Tv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_UUIfF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_zc8r5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1ckYr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_qry79_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_AoR4g_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_OECDN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_4RCEg_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_i6i0T_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_BeRJ5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_07VTp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_LZJKB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Zciur_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_pal6f_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_1m7VF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ljkt1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nosFp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_R1BvH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_V3wzR_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_9YfXv_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_yjEQb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Un4OQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_kkITx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_cv9j0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_YvAcp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_otqTp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_SbSjp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_74EQh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_K0SBG_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_vqWcD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_TCL62_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_tttSb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_dXlWT_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bO9co_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_s1t3J_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_WMU34_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_oHTrx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_c3E6V_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_wGpAu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_c86qt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_CkCNY_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_nZJoW_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_fyVOD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_3JWVq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_deGH6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_G72Pa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_X7Z8F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_0gMdd_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_EPsag_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Y7QS8_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_GNuH5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Er09o_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_p67Wp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_zAuTD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_zEJdy_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_DBjBa_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_ksQ0w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_bi9mN_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_p8o5l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_DV4v4_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_2gi8R_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_W2s1l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_VKo7f_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cSlice_9PT4h_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_id7zw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ufL35_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_T6tN0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_FXnCc_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_3XHiq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Df37m_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_f0sUV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_lPPT6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_w3zgI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_O6zGJ_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_hJrwJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_93AqC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_1R3dc_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_MGY8v_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_AIjsQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_lgx4Q_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_oSHID_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_cbmhF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_OYhJi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cReceive_IvTNs_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_8vTS2_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSend_8Jlq1_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_ezpq3_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_vFF79_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_JPfUt_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cMsg_FLPKq_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_Dw2CE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rRtYV_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_2MN9w_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_iSasi_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_XKPOH_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Ct36G_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_t3myB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TOTli_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pDCY9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eDkIr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_PX6DZ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_f9exh_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_SDM0F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_1tnL9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_eWLks_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_XPaRd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mWZkI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_y90xQ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_n7gkb_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_1VCY6_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_pTNaf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cDelay_BN0sE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_246cf_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_0qETS_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Q20mr_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_58ToI_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_yNG8l_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_kTWq5_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_z6Tfu_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_uzVoJ_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_dtbRh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_TQalo_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_MZ2oU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSlice_wk0II_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_fkMOM_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cBinop_JiUhU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_PzLB9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_5JwMx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_mpt53_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSystem_a8nL9_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_aQFrz_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_zRSvm_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cCast_A432E_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_WkqC0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_GZprb_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_WyxSB_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_tZrUC_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_rgSmX_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_FIyz7_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xs7pd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_rgNAm_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_BlMF0_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_9FeUh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DLxVF_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_jdQpl_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_DTLgh_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_Kt2kt_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_qw2XK_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_8zXeA_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cVar_Ktkhx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cBinop_RU5UD_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cUnop_vW8Ng_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cRandom_XLdXp_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_HiKFw_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_tgGut_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cMsg_u5GoE_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_7SoFL_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);
  static void cDelay_setoU_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_4Oosd_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_7rhQx_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_t9Jji_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_ilktn_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cCast_xPH6F_sendMessage(HeavyContextInterface *, int, const HvMessage *);
  static void cSwitchcase_FIH9z_onMessage(HeavyContextInterface *, void *, int letIn, const HvMessage *const, void *);

  // objects
  SignalPhasor sPhasor_1IMCa;
  SignalPhasor sPhasor_RIqN6;
  SignalPhasor sPhasor_qjSQ2;
  SignalPhasor sPhasor_Gfaxu;
  SignalPhasor sPhasor_0vXTl;
  SignalPhasor sPhasor_UluKl;
  SignalCPole sCPole_v9h3j;
  ControlVar cVar_9NFjv;
  SignalVarf sVarf_67ym6;
  ControlVar cVar_7dWL4;
  ControlVar cVar_5hbma;
  ControlBinop cBinop_ZMxXM;
  ControlDelay cDelay_v8ZuM;
  ControlBinop cBinop_EF2Sc;
  ControlBinop cBinop_Wy7Ju;
  ControlVar cVar_YS56E;
  ControlBinop cBinop_JyBRD;
  ControlBinop cBinop_3VafA;
  ControlVar cVar_fos2S;
  ControlBinop cBinop_rTnJV;
  ControlBinop cBinop_WHUIU;
  ControlBinop cBinop_0oX0u;
  ControlVar cVar_L7LpR;
  ControlBinop cBinop_NzJcu;
  ControlBinop cBinop_tnmao;
  ControlBinop cBinop_7Od2R;
  ControlSlice cSlice_Kv0OY;
  ControlSlice cSlice_QFGzm;
  ControlVar cVar_t4MMg;
  ControlBinop cBinop_QKb85;
  ControlBinop cBinop_Mrmjk;
  ControlBinop cBinop_xycem;
  ControlVar cVar_lOsqV;
  ControlSlice cSlice_FWSDw;
  ControlSlice cSlice_n37uc;
  ControlBinop cBinop_Lv4L4;
  ControlVar cVar_ZTFUx;
  ControlBinop cBinop_QlpTT;
  ControlBinop cBinop_L5JO0;
  ControlDelay cDelay_s4Z1z;
  ControlVar cVar_JOTXY;
  ControlBinop cBinop_3RPP9;
  ControlVar cVar_hSBAr;
  ControlBinop cBinop_jsyUW;
  ControlDelay cDelay_gPYKw;
  ControlRandom cRandom_8H3aC;
  ControlBinop cBinop_jGEuW;
  ControlDelay cDelay_DBt9z;
  SignalVarf sVarf_Nwd47;
  ControlVar cVar_Wh6OP;
  ControlVar cVar_DvzVb;
  ControlVar cVar_YFUfl;
  ControlBinop cBinop_muRgF;
  ControlIf cIf_VMssB;
  SignalVarf sVarf_5bgQx;
  SignalVarf sVarf_e79PD;
  ControlBinop cBinop_jOmQS;
  ControlBinop cBinop_nPYlv;
  ControlBinop cBinop_Zexmn;
  SignalVarf sVarf_Kerkt;
  ControlVar cVar_AY8Uh;
  ControlBinop cBinop_HWvS4;
  SignalVarf sVarf_xcMfN;
  ControlBinop cBinop_rL9I5;
  ControlVar cVar_SqakV;
  ControlVar cVar_JtjSa;
  ControlVar cVar_Abyfp;
  ControlBinop cBinop_QSQ2k;
  ControlBinop cBinop_Rk3VK;
  SignalVarf sVarf_756gX;
  ControlBinop cBinop_pQMK0;
  ControlDelay cDelay_NOM4H;
  ControlVar cVar_eYgpj;
  ControlDelay cDelay_2wyuM;
  ControlRandom cRandom_Eqsie;
  ControlBinop cBinop_2sEDz;
  ControlBinop cBinop_GW3Pi;
  ControlBinop cBinop_fbTJf;
  ControlVar cVar_5KHRm;
  ControlBinop cBinop_di92Z;
  ControlBinop cBinop_wpvkJ;
  ControlSlice cSlice_0kY4R;
  ControlSlice cSlice_6pahf;
  ControlVar cVar_gB4iq;
  ControlBinop cBinop_dC7h4;
  ControlVar cVar_8SYZx;
  ControlBinop cBinop_KxOFP;
  ControlBinop cBinop_Yzewn;
  ControlBinop cBinop_7sp4G;
  ControlVar cVar_hUv6z;
  ControlBinop cBinop_VfAcm;
  ControlBinop cBinop_je0M5;
  ControlBinop cBinop_YNLN3;
  ControlDelay cDelay_NQ2cl;
  ControlVar cVar_YYd6X;
  ControlBinop cBinop_M1eXG;
  ControlBinop cBinop_oPLhX;
  ControlBinop cBinop_tTpWz;
  ControlVar cVar_P7BSw;
  ControlSlice cSlice_KdFy6;
  ControlSlice cSlice_6G4Ne;
  ControlVar cVar_UUIfF;
  ControlVar cVar_qry79;
  ControlBinop cBinop_AoR4g;
  ControlBinop cBinop_4RCEg;
  ControlRandom cRandom_i6i0T;
  ControlBinop cBinop_LZJKB;
  ControlBinop cBinop_1m7VF;
  ControlBinop cBinop_Ljkt1;
  ControlBinop cBinop_R1BvH;
  ControlBinop cBinop_V3wzR;
  ControlBinop cBinop_Un4OQ;
  ControlVar cVar_kkITx;
  ControlVar cVar_YvAcp;
  ControlVar cVar_otqTp;
  ControlVar cVar_TCL62;
  ControlBinop cBinop_tttSb;
  ControlBinop cBinop_WMU34;
  ControlBinop cBinop_c3E6V;
  ControlSlice cSlice_c86qt;
  ControlSlice cSlice_CkCNY;
  ControlVar cVar_fyVOD;
  ControlBinop cBinop_3JWVq;
  ControlVar cVar_GNuH5;
  ControlVar cVar_Er09o;
  ControlBinop cBinop_p67Wp;
  ControlBinop cBinop_zAuTD;
  ControlBinop cBinop_p8o5l;
  ControlDelay cDelay_DV4v4;
  ControlSlice cSlice_W2s1l;
  ControlSlice cSlice_9PT4h;
  ControlBinop cBinop_id7zw;
  ControlDelay cDelay_3XHiq;
  ControlVar cVar_f0sUV;
  ControlDelay cDelay_hJrwJ;
  ControlBinop cBinop_93AqC;
  SignalVarf sVarf_4srE8;
  ControlVar cVar_lgx4Q;
  ControlVar cVar_oSHID;
  SignalVarf sVarf_VMnUs;
  SignalVarf sVarf_8XRWS;
  ControlVar cVar_cbmhF;
  ControlVar cVar_8vTS2;
  ControlDelay cDelay_vFF79;
  ControlBinop cBinop_rRtYV;
  ControlVar cVar_2MN9w;
  ControlBinop cBinop_Ct36G;
  ControlBinop cBinop_TOTli;
  ControlVar cVar_1tnL9;
  ControlBinop cBinop_y90xQ;
  ControlBinop cBinop_1VCY6;
  ControlDelay cDelay_BN0sE;
  ControlBinop cBinop_246cf;
  ControlBinop cBinop_Q20mr;
  ControlBinop cBinop_58ToI;
  ControlVar cVar_z6Tfu;
  ControlSlice cSlice_uzVoJ;
  ControlSlice cSlice_dtbRh;
  ControlBinop cBinop_TQalo;
  ControlSlice cSlice_MZ2oU;
  ControlSlice cSlice_wk0II;
  ControlBinop cBinop_JiUhU;
  ControlBinop cBinop_PzLB9;
  ControlVar cVar_GZprb;
  ControlVar cVar_WyxSB;
  ControlVar cVar_FIyz7;
  ControlBinop cBinop_rgNAm;
  ControlVar cVar_9FeUh;
  ControlBinop cBinop_jdQpl;
  ControlBinop cBinop_Kt2kt;
  ControlBinop cBinop_qw2XK;
  ControlBinop cBinop_8zXeA;
  ControlVar cVar_Ktkhx;
  ControlBinop cBinop_RU5UD;
  ControlRandom cRandom_XLdXp;
  SignalVarf sVarf_2Ke1c;
  ControlDelay cDelay_setoU;
  SignalVarf sVarf_SqjYg;
};

#endif // _HEAVY_CONTEXT_WAKEFIELD_HPP_
